### ISSUE TITLE
Remove auto updater

### ISSUE THREAD

**Issue by weakit** [Shravan-1908/iris#1]
An auto-updater sounds cumbersome and is probably prone to issues.

Distributing via [chocolatey](https://chocolatey.org/) or [scoop](https://scoop.sh/) is probably a better idea.

An update notification sounds nice too.

**Comment by shravanasati** [comment]
Sounds convincing, I decided I'll distribute the next upgrade via a package manager.
Thanks for pointing out the security vulnerabilities.
