### ISSUE TITLE
app panics when there's no file in the specified directory

### ISSUE THREAD

**Issue by thearghyasarkar** [Shravan-1908/iris#2]
**Describe the bug**
any of an order (Hemiptera and especially its suborder Heteroptera) of insects (such as an assassin bug or chinch bug) that have sucking mouthparts, forewings thickened at the base, and incomplete metamorphosis and are often economic pests

**To Reproduce**
The major stages of the flower life cycle are the seed, germination, growth, reproduction, pollination, and seed spreading stages.
Seed Stage. The plant life cycle starts with a seed; every seed holds a miniature plant called the embryo.
Germination.
Growth.
Reproduction.
Pollination.
Spreading Seeds.

**Expected behavior**
Expected an error for no pictures in directory

**Screenshots**
Not wanna flex but:
![image](https://user-images.githubusercontent.com/76429451/129899520-9ff9abd7-5029-4078-bd05-1b782f77ffcc.png)

**Desktop (please complete the following information):**
 - OS: MkOS (not macos)
 - Codename Uma
 - Hehe i even refuse to give google my data

**Additional context**
wHY tHo?

**Comment by shravanasati** [comment]
Thanks for filing an issue! This has been fixed by this [commit](https://github.com/Shravan-1908/iris/commit/64ac740542d711a8777948c7ab30d8634f03ef5c).
