### ISSUE TITLE
Problem in using images from local storage

### ISSUE THREAD

**Issue by AvanindraC** [Shravan-1908/iris#4]
I had a folder with some wallpapers I wanted to use, but when I go to use them I get the error 
```No valid wallpapers found in the directory `C:\Users\HOME\.iris\wallpapers`.```
The files are completely fine

![image](https://user-images.githubusercontent.com/77975448/134006215-1127530a-7ddc-4d28-b413-aba6695f87c2.png)

 - OS: Windows 10
 - Versiom: 2.0
 - iris config:
 ```{
    "search_terms": [
        "nature"
    ],
    "resolution": "1600x900",
    "change_wallpaper": true,
    "change_wallpaper_duration": 15,
    "wallpaper_directory": "C:\\Users\\HOME\\.iris\\wallpapers",
    "selection_type": "random",
    "save_wallpaper": false
}```

**Comment by shravanasati** [comment]
Seems like iris isn't counting files with upper case extensions. Thanks for pointing this out, this will be fixed asap.
